/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AssetInfo: typeof import('./src/components/AssetInfo.vue')['default']
    Company: typeof import('./src/components/Company.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
  }
}
