-- MySQL Script generated by MySQL Workbench
-- Thu Mar 19 11:03:19 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tigersan_web
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tigersan_web
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tigersan_web` DEFAULT CHARACTER SET utf8 ;
USE `tigersan_web` ;

-- -----------------------------------------------------
-- Table `tigersan_web`.`company_mgt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tigersan_web`.`company_mgt` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `addr` VARCHAR(100) NOT NULL,
  `parent` BIGINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `index_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tigersan_web`.`role_mgt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tigersan_web`.`role_mgt` (
  `id` BIGINT NOT NULL,
  `company` BIGINT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `index_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_role_mgt_company_mgt1_idx` (`company` ASC) VISIBLE,
  CONSTRAINT `fk_role_mgt_company_mgt1`
    FOREIGN KEY (`company`)
    REFERENCES `tigersan_web`.`company_mgt` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tigersan_web`.`person_mgt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tigersan_web`.`person_mgt` (
  `id` BIGINT NOT NULL,
  `role` BIGINT NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `nickname` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `photo` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `index_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  INDEX `fk_person_mgt_role_mgt1_idx` (`role` ASC) VISIBLE,
  CONSTRAINT `fk_person_mgt_role_mgt1`
    FOREIGN KEY (`role`)
    REFERENCES `tigersan_web`.`role_mgt` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tigersan_web`.`admin_mgt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tigersan_web`.`admin_mgt` (
  `id` BIGINT NOT NULL,
  `company` BIGINT NULL,
  `name` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `is_root` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `index_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_admin_mgt_company_mgt1_idx` (`company` ASC) VISIBLE,
  CONSTRAINT `fk_admin_mgt_company_mgt1`
    FOREIGN KEY (`company`)
    REFERENCES `tigersan_web`.`company_mgt` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tigersan_web`.`authority_mgt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tigersan_web`.`authority_mgt` (
  `id` BIGINT NOT NULL,
  `role` BIGINT NOT NULL,
  `path` VARCHAR(100) NOT NULL,
  `is_readonly` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `index_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_authority_mgt_role_mgt1_idx` (`role` ASC) VISIBLE,
  CONSTRAINT `fk_authority_mgt_role_mgt1`
    FOREIGN KEY (`role`)
    REFERENCES `tigersan_web`.`role_mgt` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
