-- MySQL Script generated by MySQL Workbench
-- Thu Aug  6 14:09:50 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tigersan_web
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tigersan_web
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tigersan_web` DEFAULT CHARACTER SET utf8 ;
USE `tigersan_web` ;

-- -----------------------------------------------------
-- Table `tigersan_web`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tigersan_web`.`company` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `addr` VARCHAR(100) NOT NULL,
  `parent` BIGINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `index_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tigersan_web`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tigersan_web`.`department` (
  `id` BIGINT NOT NULL,
  `company` BIGINT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `index_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_department_mgt_company_mgt1_idx` (`company` ASC) VISIBLE,
  CONSTRAINT `fk_department_mgt_company_mgt1`
    FOREIGN KEY (`company`)
    REFERENCES `tigersan_web`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tigersan_web`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tigersan_web`.`role` (
  `id` BIGINT NOT NULL,
  `department` BIGINT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `index_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_role_department1_idx` (`department` ASC) VISIBLE,
  CONSTRAINT `fk_role_department1`
    FOREIGN KEY (`department`)
    REFERENCES `tigersan_web`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tigersan_web`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tigersan_web`.`person` (
  `id` BIGINT NOT NULL,
  `role` BIGINT NOT NULL,
  `is_admin` TINYINT(1) NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `nickname` VARCHAR(50) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `avatar` VARCHAR(100) NULL,
  `phone` VARCHAR(50) NULL,
  `mail` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `index_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_person_mgt_role_mgt1_idx` (`role` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `nickname_UNIQUE` (`nickname` ASC) VISIBLE,
  CONSTRAINT `fk_person_mgt_role_mgt1`
    FOREIGN KEY (`role`)
    REFERENCES `tigersan_web`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tigersan_web`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tigersan_web`.`admin` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `index_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tigersan_web`.`authority`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tigersan_web`.`authority` (
  `id` BIGINT NOT NULL,
  `role` BIGINT NOT NULL,
  `path` VARCHAR(100) NOT NULL,
  `is_readonly` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `index_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_authority_mgt_role_mgt1_idx` (`role` ASC) VISIBLE,
  CONSTRAINT `fk_authority_mgt_role_mgt1`
    FOREIGN KEY (`role`)
    REFERENCES `tigersan_web`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tigersan_web`.`site_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tigersan_web`.`site_type` (
  `id` BIGINT NOT NULL,
  `company` BIGINT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `index_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_site_type_company1_idx` (`company` ASC) VISIBLE,
  CONSTRAINT `fk_site_type_company1`
    FOREIGN KEY (`company`)
    REFERENCES `tigersan_web`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tigersan_web`.`site`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tigersan_web`.`site` (
  `id` BIGINT NOT NULL,
  `company` BIGINT NOT NULL,
  `type` BIGINT NOT NULL,
  `code` VARCHAR(50) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `addr` VARCHAR(100) NOT NULL,
  `addr_detail` VARCHAR(100) NOT NULL,
  `longitude` DOUBLE NOT NULL,
  `latitude` DOUBLE NOT NULL,
  `fence_path` VARCHAR(500) NULL,
  `manager` VARCHAR(50) NULL,
  `phone` VARCHAR(50) NULL,
  `comment` VARCHAR(200) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `index_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_admin_mgt_company_mgt1_idx` (`company` ASC) VISIBLE,
  INDEX `fk_site_site_type1_idx` (`type` ASC) VISIBLE,
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE,
  CONSTRAINT `fk_admin_mgt_company_mgt10`
    FOREIGN KEY (`company`)
    REFERENCES `tigersan_web`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_site_site_type1`
    FOREIGN KEY (`type`)
    REFERENCES `tigersan_web`.`site_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tigersan_web`.`station_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tigersan_web`.`station_type` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `index_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tigersan_web`.`base_station`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tigersan_web`.`base_station` (
  `id` BIGINT NOT NULL,
  `type` BIGINT NOT NULL,
  `site` BIGINT NOT NULL,
  `is_enable` TINYINT(1) NOT NULL,
  `is_mobile` TINYINT(1) NOT NULL,
  `online_state` TINYINT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `mac_addr` VARCHAR(50) NOT NULL,
  `heartbeat_interval` INT NOT NULL,
  `report_interval` INT NOT NULL,
  `month_offline` BIGINT NOT NULL,
  `create_time` DATETIME NOT NULL,
  `report_time` DATETIME NULL,
  `location_mode` TINYINT NULL,
  `longitude` DOUBLE NULL,
  `latitude` DOUBLE NULL,
  `image` VARCHAR(50) NULL,
  INDEX `fk_base_station_site1_idx` (`site` ASC) VISIBLE,
  INDEX `fk_base_station_eqp_type1_idx` (`type` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `mac_addr_UNIQUE` (`mac_addr` ASC) VISIBLE,
  CONSTRAINT `fk_base_station_site1`
    FOREIGN KEY (`site`)
    REFERENCES `tigersan_web`.`site` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_base_station_eqp_type1`
    FOREIGN KEY (`type`)
    REFERENCES `tigersan_web`.`station_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tigersan_web`.`scenario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tigersan_web`.`scenario` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `index_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tigersan_web`.`batch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tigersan_web`.`batch` (
  `id` BIGINT NOT NULL,
  `company` BIGINT NOT NULL,
  `scenario` BIGINT NOT NULL,
  `batch_id` VARCHAR(50) NOT NULL,
  `shipment_time` DATETIME NOT NULL,
  `manager` VARCHAR(50) NULL,
  `phone` VARCHAR(50) NULL,
  `comment` VARCHAR(200) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `index_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_tag_company1_idx` (`company` ASC) VISIBLE,
  INDEX `fk_tag_scenario1_idx` (`scenario` ASC) VISIBLE,
  CONSTRAINT `fk_tag_company1`
    FOREIGN KEY (`company`)
    REFERENCES `tigersan_web`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tag_scenario1`
    FOREIGN KEY (`scenario`)
    REFERENCES `tigersan_web`.`scenario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tigersan_web`.`tag_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tigersan_web`.`tag_type` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `index_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tigersan_web`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tigersan_web`.`tag` (
  `id` BIGINT NOT NULL,
  `batch` BIGINT NOT NULL,
  `type` BIGINT NOT NULL,
  `station` BIGINT NULL,
  `eqp_type` TINYINT NOT NULL,
  `is_fall` TINYINT(1) NULL,
  `is_enable` TINYINT(1) NOT NULL,
  `online_state` TINYINT NOT NULL,
  `location_mode` TINYINT NULL,
  `tag_id` VARCHAR(50) NOT NULL,
  `asset` BIGINT NULL,
  `asset_id` VARCHAR(50) NULL,
  `rfid` VARCHAR(50) NULL,
  `imei` VARCHAR(50) NULL,
  `iccid` VARCHAR(50) NULL,
  `battery` INT NULL,
  `signal` INT NULL,
  `temperature` DOUBLE NULL,
  `longitude` DOUBLE NULL,
  `latitude` DOUBLE NULL,
  `comment` VARCHAR(200) NULL,
  `report_time` DATETIME NULL,
  `image` VARCHAR(50) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `index_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `tag_id_UNIQUE` (`tag_id` ASC) VISIBLE,
  INDEX `fk_tag_base_station1_idx` (`station` ASC) VISIBLE,
  INDEX `fk_tag_batch1_idx` (`batch` ASC) VISIBLE,
  INDEX `fk_tag_tag_type1_idx` (`type` ASC) VISIBLE,
  CONSTRAINT `fk_tag_base_station1`
    FOREIGN KEY (`station`)
    REFERENCES `tigersan_web`.`base_station` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tag_batch1`
    FOREIGN KEY (`batch`)
    REFERENCES `tigersan_web`.`batch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tag_tag_type1`
    FOREIGN KEY (`type`)
    REFERENCES `tigersan_web`.`tag_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tigersan_web`.`asset_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tigersan_web`.`asset_type` (
  `id` BIGINT NOT NULL,
  `company` BIGINT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `index_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_asset_type_company1_idx` (`company` ASC) VISIBLE,
  CONSTRAINT `fk_asset_type_company1`
    FOREIGN KEY (`company`)
    REFERENCES `tigersan_web`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tigersan_web`.`vehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tigersan_web`.`vehicle` (
  `id` BIGINT NOT NULL,
  `company` BIGINT NOT NULL,
  `plate` VARCHAR(50) NOT NULL,
  `logistics` VARCHAR(50) NULL,
  `driver` VARCHAR(50) NULL,
  `phone` VARCHAR(50) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `index_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_vehicle_company1_idx` (`company` ASC) VISIBLE,
  UNIQUE INDEX `plate_UNIQUE` (`plate` ASC) VISIBLE,
  CONSTRAINT `fk_vehicle_company1`
    FOREIGN KEY (`company`)
    REFERENCES `tigersan_web`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tigersan_web`.`asset`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tigersan_web`.`asset` (
  `id` BIGINT NOT NULL,
  `department` BIGINT NOT NULL,
  `type` BIGINT NOT NULL,
  `asset_id` VARCHAR(50) NOT NULL,
  `is_fall` TINYINT(1) NULL,
  `is_auto` TINYINT(1) NOT NULL,
  `state` TINYINT NOT NULL,
  `online_state` TINYINT NOT NULL,
  `error_type` TINYINT NULL,
  `tag` BIGINT NULL,
  `tag_id` VARCHAR(50) NULL,
  `tag_type` BIGINT NULL,
  `station` BIGINT NULL,
  `vehicle` BIGINT NULL,
  `transfer` BIGINT NULL,
  `last_record` BIGINT NULL,
  `name` VARCHAR(50) NULL,
  `comment` VARCHAR(100) NULL,
  `binding_time` DATETIME NULL,
  `calculation_time` DATETIME NULL,
  `daily_move` INT NULL,
  `monthly_move` INT NULL,
  `total_move` INT NULL,
  `stay_duration` DOUBLE NULL,
  `travel_duration` DOUBLE NULL,
  `offline_duration` DOUBLE NULL,
  INDEX `fk_Asset_department1_idx` (`department` ASC) VISIBLE,
  INDEX `fk_asset_asset_type1_idx` (`type` ASC) VISIBLE,
  INDEX `fk_asset_tag1_idx` (`tag` ASC) VISIBLE,
  UNIQUE INDEX `asset_id_UNIQUE` (`asset_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_asset_tag_type1_idx` (`tag_type` ASC) VISIBLE,
  INDEX `fk_asset_vehicle1_idx` (`vehicle` ASC) VISIBLE,
  INDEX `fk_asset_base_station1_idx` (`station` ASC) VISIBLE,
  CONSTRAINT `fk_Asset_department1`
    FOREIGN KEY (`department`)
    REFERENCES `tigersan_web`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asset_asset_type1`
    FOREIGN KEY (`type`)
    REFERENCES `tigersan_web`.`asset_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asset_tag1`
    FOREIGN KEY (`tag`)
    REFERENCES `tigersan_web`.`tag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asset_tag_type1`
    FOREIGN KEY (`tag_type`)
    REFERENCES `tigersan_web`.`tag_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asset_vehicle1`
    FOREIGN KEY (`vehicle`)
    REFERENCES `tigersan_web`.`vehicle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asset_base_station1`
    FOREIGN KEY (`station`)
    REFERENCES `tigersan_web`.`base_station` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tigersan_web`.`asset_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tigersan_web`.`asset_record` (
  `id` BIGINT NOT NULL,
  `asset` BIGINT NOT NULL,
  `tag` BIGINT NOT NULL,
  `site` BIGINT NULL,
  `target_site` BIGINT NULL,
  `report_time` DATETIME NOT NULL,
  `state` TINYINT NOT NULL,
  `online_state` TINYINT NOT NULL,
  `location_mode` TINYINT NULL,
  `battery` INT NULL,
  `signal` INT NULL,
  `temperature` DOUBLE NULL,
  `longitude` DOUBLE NULL,
  `latitude` DOUBLE NULL,
  `address` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `index_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_asset_record_asset1_idx` (`asset` ASC) VISIBLE,
  INDEX `fk_asset_record_site1_idx` (`site` ASC) VISIBLE,
  INDEX `fk_asset_record_tag1_idx` (`tag` ASC) VISIBLE,
  INDEX `fk_asset_record_site2_idx` (`target_site` ASC) VISIBLE,
  CONSTRAINT `fk_asset_record_asset1`
    FOREIGN KEY (`asset`)
    REFERENCES `tigersan_web`.`asset` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asset_record_site1`
    FOREIGN KEY (`site`)
    REFERENCES `tigersan_web`.`site` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asset_record_tag1`
    FOREIGN KEY (`tag`)
    REFERENCES `tigersan_web`.`tag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asset_record_site2`
    FOREIGN KEY (`target_site`)
    REFERENCES `tigersan_web`.`site` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tigersan_web`.`binding_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tigersan_web`.`binding_record` (
  `id` BIGINT NOT NULL,
  `asset` BIGINT NOT NULL,
  `tag` BIGINT NOT NULL,
  `is_binding` TINYINT(1) NOT NULL,
  `time` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `index_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_admin_copy1_tag1_idx` (`tag` ASC) VISIBLE,
  INDEX `fk_admin_copy1_asset1_idx` (`asset` ASC) VISIBLE,
  CONSTRAINT `fk_admin_copy1_tag1`
    FOREIGN KEY (`tag`)
    REFERENCES `tigersan_web`.`tag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_admin_copy1_asset1`
    FOREIGN KEY (`asset`)
    REFERENCES `tigersan_web`.`asset` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tigersan_web`.`transfer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tigersan_web`.`transfer` (
  `id` BIGINT NOT NULL,
  `asset` BIGINT NOT NULL,
  `site` BIGINT NOT NULL,
  `target` BIGINT NOT NULL,
  `code` VARCHAR(50) NOT NULL,
  `asset_id` VARCHAR(50) NOT NULL,
  `start_time` DATETIME NOT NULL,
  `end_time` DATETIME NULL,
  `plate` VARCHAR(50) NULL,
  `logistics` VARCHAR(50) NULL,
  `driver` VARCHAR(50) NULL,
  `phone` VARCHAR(50) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `index_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`code` ASC) VISIBLE,
  INDEX `fk_transfer_asset1_idx` (`asset` ASC) VISIBLE,
  INDEX `fk_transfer_site1_idx` (`site` ASC) VISIBLE,
  INDEX `fk_transfer_site2_idx` (`target` ASC) VISIBLE,
  CONSTRAINT `fk_transfer_asset1`
    FOREIGN KEY (`asset`)
    REFERENCES `tigersan_web`.`asset` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transfer_site1`
    FOREIGN KEY (`site`)
    REFERENCES `tigersan_web`.`site` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transfer_site2`
    FOREIGN KEY (`target`)
    REFERENCES `tigersan_web`.`site` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tigersan_web`.`inventory_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tigersan_web`.`inventory_record` (
  `id` BIGINT NOT NULL,
  `site` BIGINT NOT NULL,
  `in_store` INT NOT NULL,
  `stolid` INT NOT NULL,
  `add` INT NOT NULL,
  `reduce` INT NOT NULL,
  `time` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `index_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_asset_inventory_site1_idx` (`site` ASC) VISIBLE,
  CONSTRAINT `fk_asset_inventory_site1`
    FOREIGN KEY (`site`)
    REFERENCES `tigersan_web`.`site` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
