import { TextModel } from "./models/Text/TextModel"

/** 文本集合 */
export class Texts {
    // A:
    static readonly Add = TextModel.Computed('Add', '新增')
    static readonly All = TextModel.Computed('All', '全部')
    static readonly Age = TextModel.Computed('Age', '年龄')
    static readonly Auto = TextModel.Computed('Auto', '自动')
    static readonly Addr = TextModel.Computed('Addr', '地址')
    static readonly Asset = TextModel.Computed('Asset', '资产')
    static readonly Allot = TextModel.Computed('Allot', '调拨')
    static readonly Address = TextModel.Computed('Address', '地址')
    static readonly AssetId = TextModel.Computed('AssetId', '资产ID')
    static readonly AllotMode = TextModel.Computed('AllotMode', '调拨方式')
    static readonly AssetType = TextModel.Computed('AssetType', '资产类型')
    static readonly Authorities = TextModel.Computed('Authorities', '权限')
    static readonly AddrDetail = TextModel.Computed('AddrDetail', '详细地址')
    static readonly AssetState = TextModel.Computed('AssetState', '资产状态')
    static readonly AssetDetail = TextModel.Computed('AssetDetail', '资产详情')
    static readonly AddedSuccessfully = TextModel.Computed('Added successfully', '添加成功')
    // B:
    static readonly Base = TextModel.Computed('Base', '基础')
    static readonly Back = TextModel.Computed('Back', '返回')
    static readonly Batch = TextModel.Computed('Batch', '批次')
    static readonly Bound = TextModel.Computed('Bound', '已绑定')
    static readonly Binding = TextModel.Computed('Binding', '绑定')
    static readonly Battery = TextModel.Computed('Battery', '电量')
    static readonly Birthday = TextModel.Computed('Birthday', '生日')
    static readonly Breakdown = TextModel.Computed('Breakdown', '故障')
    static readonly Business = TextModel.Computed('Business', '业务平台')
    static readonly BaseStation = TextModel.Computed('BaseStation', '基站')
    static readonly BasicDetail = TextModel.Computed('BasicDetail', '基础详情')
    static readonly BindingTime = TextModel.Computed('BindingTime', '绑定时间')
    static readonly BindingState = TextModel.Computed('BindingState', '绑定状态')
    static readonly BasicSettings = TextModel.Computed('BasicSettings', '基础设置')
    // C:
    static readonly Colon = TextModel.Computed(': ', '：')
    static readonly Code = TextModel.Computed('Code', '编号')
    static readonly Clear = TextModel.Computed('Clear', '清空')
    static readonly Count = TextModel.Computed('Count', '总数')
    static readonly Chart = TextModel.Computed('Chart', '图表')
    static readonly Cancel = TextModel.Computed('Cancel', '取消')
    static readonly Comment = TextModel.Computed('Comment', '备注')
    static readonly Company = TextModel.Computed('Company', '公司')
    static readonly Confirm = TextModel.Computed('Confirm ', '确认')
    static readonly Captcha = TextModel.Computed('Captcha', '验证码')
    static readonly CreateDir = TextModel.Computed('CreateDir', '新建文件夹')
    static readonly CreateTime = TextModel.Computed('CreateTime', '创建时间')
    static readonly CalculateTime = TextModel.Computed('CalculateTime', '计算时间')
    static readonly CannotBeEmpty = TextModel.Computed('Cannot be empty!', '不可为空')
    static readonly ChangePassword = TextModel.Computed('Change password ', '修改密码')
    static readonly ConfirmPassword = TextModel.Computed('ConfirmPassword ', '确认密码')
    static readonly CannotBeLessThan = TextModel.Computed('Cannot be less than ', '不可小于')
    static readonly CannotBeGreaterThan = TextModel.Computed('Cannot be greater than ', '不可大于')
    static readonly CannotContainSpaces = TextModel.Computed('Cannot contain spaces!', '不可包含空格')
    static readonly ContainsIllegalCharacters = TextModel.Computed('Contains illegal characters!', '包含非法字符')
    // D:
    static readonly Done = TextModel.Computed('Done', '完成')
    static readonly DIR = TextModel.Computed('DIR', '文件夹')
    static readonly Delete = TextModel.Computed('Delete', '删除')
    static readonly Driver = TextModel.Computed('Driver', '司机')
    static readonly Dialog = TextModel.Computed('Dialog', '对话框')
    static readonly Disable = TextModel.Computed('Disable', '禁用')
    static readonly DailyMove = TextModel.Computed('DailyMove', '日周转')
    static readonly Department = TextModel.Computed('Department', '部门')
    static readonly DeletedSuccessfully = TextModel.Computed('Deleted successfully', '删除成功')
    static readonly DownloadSuccessfully = TextModel.Computed('Download successfully', '下载成功')
    static readonly DeleteConfirm = TextModel.Computed('Are you sure you want to delete it? ', '是否确定删除？')
    // E:
    static readonly Empty = TextModel.Computed('', '')
    static readonly End = TextModel.Computed('End', '结束')
    static readonly Edit = TextModel.Computed('Edit', '修改')
    static readonly Error = TextModel.Computed('Error', '错误')
    static readonly Enable = TextModel.Computed('Enable', '启用')
    static readonly EndTime = TextModel.Computed('EndTime', '结束时间')
    static readonly EqpName = TextModel.Computed('EqpName', '设备名称')
    static readonly EqpType = TextModel.Computed('EqpType', '设备类型')
    static readonly EditTime = TextModel.Computed('EditTime', '修改时间')
    static readonly ErrorType = TextModel.Computed('ErrorType', '异常类型')
    static readonly EditedSuccessfully = TextModel.Computed('Edited Successfully', '修改成功')
    // F:
    static readonly Fall = TextModel.Computed('Fall', '脱落')
    static readonly Form = TextModel.Computed('Form', '表单')
    static readonly File = TextModel.Computed('File', '文件')
    static readonly FILE = TextModel.Computed('FILE', '文件')
    static readonly Fence = TextModel.Computed('Fence', '围栏')
    static readonly Female = TextModel.Computed('Female', '女')
    static readonly Feedback = TextModel.Computed('Feedback', '反馈')
    static readonly FileType = TextModel.Computed('FileType', '文件类型')
    static readonly FencePath = TextModel.Computed('FencePath', '围栏路径')
    static readonly Feedforward = TextModel.Computed('Feedforward', '前馈')
    static readonly FallDetect = TextModel.Computed('FallDetect', '脱落检测')
    // G:
    static readonly Gender = TextModel.Computed('Gender', '性别')
    // H:
    static readonly Help = TextModel.Computed('Help', '帮助')
    // I:
    static readonly Is = TextModel.Computed('Is', '是否')
    static readonly Input = TextModel.Computed('Input', '输入')
    static readonly IsEnd = TextModel.Computed('IsEnd', '是否完成')
    static readonly IsFall = TextModel.Computed('IsFall', '是否脱落')
    static readonly Inbound = TextModel.Computed('Inbound', '入库')
    static readonly InStore = TextModel.Computed('InStore', '在库')
    static readonly InTransit = TextModel.Computed('InTransit', '在途')
    static readonly IsEnable = TextModel.Computed('IsEnable', '激活状态')
    static readonly IsBinding = TextModel.Computed('IsBinding', '是否绑定')
    static readonly Information = TextModel.Computed('Information', '信息')
    static readonly IsReadonly = TextModel.Computed('IsReadonly: ', '是否只读：')
    static readonly InTransitTimeout = TextModel.Computed('InTransitTimeout', '在途超时')
    static readonly IncorrectFormat = TextModel.Computed('Incorrect format!', '格式不正确')
    static readonly IncorrectCaptcha = TextModel.Computed('Incorrect captcha!', '验证码不正确')
    static readonly InboundSuccessful = TextModel.Computed('Inbound operation successful', '入库成功')
    static readonly IncorrectMacAddr = TextModel.Computed('The MAC address format is incorrect!', 'MAC地址格式不正确')
    // J:
    static readonly JoiningTime = TextModel.Computed('JoiningTime', '加入时间')
    // L:
    static readonly Lose = TextModel.Computed('Lose', '丢失')
    static readonly Login = TextModel.Computed('Login', '登录')
    static readonly Loading = TextModel.Computed('Loading', '加载')
    static readonly Language = TextModel.Computed('Language', '语言')
    static readonly Locator = TextModel.Computed('Locator', '定位器')
    static readonly Latitude = TextModel.Computed('Latitude', '纬度')
    static readonly Longitude = TextModel.Computed('Longitude', '经度')
    static readonly Logistics = TextModel.Computed('Logistics', '物流')
    static readonly LocationMode = TextModel.Computed('LocationMode', '定位方式')
    static readonly LastReportTime = TextModel.Computed('LastReportTime', '最后上报时间')
    static readonly LogoutConfirm = TextModel.Computed('Do you want to log out?', '是否退出登录？')
    static readonly LengthCannotBeLessThan = TextModel.Computed('The length cannot be less than ', '长度不可小于')
    static readonly LengthCannotBeGreaterThan = TextModel.Computed('The length cannot be greater than ', '长度不可大于')
    // M:
    static readonly Male = TextModel.Computed('Male', '男')
    static readonly Mail = TextModel.Computed('Mail', '邮箱')
    static readonly Manual = TextModel.Computed('Manual', '手动')
    static readonly Manager = TextModel.Computed('Manager', '联系人')
    static readonly MacAddr = TextModel.Computed('MacAddr', 'MAC地址')
    static readonly MonthlyMove = TextModel.Computed('MonthlyMove', '月周转')
    static readonly MustContainLetter = TextModel.Computed('It must contain at least one letter!', '必须包含至少一个字母')
    static readonly MustContainNumber = TextModel.Computed('It must contain at least one number!', '必须包含至少一个数字')
    static readonly MustContainCapital = TextModel.Computed('It must contain at least one capital letter!', '必须包含至少一个大写字母')
    static readonly MustContainLowercase = TextModel.Computed('It must contain at least one lowercase letter!', '必须包含至少一个小写字母')
    static readonly MustContainSpecialCharacter = TextModel.Computed('It must contain at least one special character!', '必须包含至少一个特殊字符')
    // N:
    static readonly No = TextModel.Computed('No', '否')
    static readonly Null = TextModel.Computed('null', 'null')
    static readonly Name = TextModel.Computed('Name', '名称')
    static readonly Normal = TextModel.Computed('Normal', '正常')
    static readonly Nickname = TextModel.Computed('Nickname', '昵称')
    static readonly NoSignal = TextModel.Computed('NoSignal', '无信号')
    static readonly NoRecord = TextModel.Computed('NoRecord', '无记录')
    static readonly NoContent = TextModel.Computed('No Content', '无内容')
    static readonly NewPassword = TextModel.Computed('NewPassword', '新密码')
    static readonly NotEqual = TextModel.Computed('Values are not equal', '值不相等')
    // O:
    static readonly Ok = TextModel.Computed('Ok', '确定')
    static readonly Other = TextModel.Computed('Other', '其它')
    static readonly Output = TextModel.Computed('Output', '输出')
    static readonly Origin = TextModel.Computed('Origin', '起点')
    static readonly Online = TextModel.Computed('Online', '在线')
    static readonly Offline = TextModel.Computed('Offline', '离线')
    static readonly Outbound = TextModel.Computed('Outbound', '出库')
    static readonly Operation = TextModel.Computed('Operation', '操作')
    static readonly OldPassword = TextModel.Computed('OldPassword', '旧密码')
    static readonly OnlineState = TextModel.Computed('OnlineState', '在线状态')
    static readonly OperationSuccessful = TextModel.Computed('Operation successful', '操作成功')
    static readonly OnlyNumbersAllowed = TextModel.Computed('Only numbers allowed!', '只能包含数字')
    static readonly OutboundSuccessful = TextModel.Computed('Outbound operation successful', '出库成功')
    // P:
    static readonly Pie = TextModel.Computed('Pie', '饼图')
    static readonly page = TextModel.Computed('page', '页')
    static readonly Phone = TextModel.Computed('Phone', '电话')
    static readonly Plate = TextModel.Computed('Plate', '车牌号')
    static readonly Parent = TextModel.Computed('Parent', '父级')
    static readonly Preview = TextModel.Computed('Preview', '预览')
    static readonly Percent = TextModel.Computed('Percent', '百分比')
    static readonly Password = TextModel.Computed('Password', '密码')
    static readonly Progress = TextModel.Computed('Progress', '进度')
    static readonly PleaseEnter = TextModel.Computed('Please enter.', '请输入')
    static readonly PleaseSelect = TextModel.Computed('Please select.', '请选择')
    static readonly PleaseEnterANumber = TextModel.Computed('Please enter a number', '请输入数字')
    // R:
    static readonly Role = TextModel.Computed('Role', '角色')
    static readonly Reduce = TextModel.Computed('Reduce', '减少')
    static readonly Repair = TextModel.Computed('Repair', '维修')
    static readonly Rename = TextModel.Computed('Rename', '重命名')
    static readonly Refresh = TextModel.Computed('Refresh', '刷新')
    static readonly ReportTime = TextModel.Computed('ReportTime', '上报时间')
    // S:
    static readonly Save = TextModel.Computed('Save', '保存')
    static readonly Size = TextModel.Computed('Size', '大小')
    static readonly Site = TextModel.Computed('Site', '场地')
    static readonly Stop = TextModel.Computed('Stop', '停止')
    static readonly State = TextModel.Computed('State', '状态')
    static readonly Submit = TextModel.Computed('Submit', '提交')
    static readonly Stolid = TextModel.Computed('Stolid', '滞留')
    static readonly Select = TextModel.Computed('Select', '选中')
    static readonly Signal = TextModel.Computed('Signal', '信号')
    static readonly Salary = TextModel.Computed('Salary', '薪资')
    static readonly Seconds = TextModel.Computed('Seconds', '秒')
    static readonly Success = TextModel.Computed('Success', '成功')
    static readonly Station = TextModel.Computed('Station', '站点')
    static readonly Scenario = TextModel.Computed('Scenario', '场景')
    static readonly SelectAll = TextModel.Computed('SelectAll', '全选')
    static readonly SiteType = TextModel.Computed('SiteType', '场地类型')
    static readonly StationId = TextModel.Computed('StationId', '基站ID')
    static readonly StartTime = TextModel.Computed('StartTime', '开始时间')
    static readonly ShipmentTime = TextModel.Computed('ShipmentTime', '出货')
    static readonly StationType = TextModel.Computed('StationType', '基站类型')
    static readonly StationDetail = TextModel.Computed('StationDetail', '基站详情')
    static readonly SystemSettings = TextModel.Computed('SystemSettings', '系统设置')
    static readonly SubmittedSuccessfully = TextModel.Computed('Submitted Successfully', '提交成功')
    // T:
    static readonly To = TextModel.Computed('To', '到')
    static readonly Tag = TextModel.Computed('Tag', '标签')
    static readonly Time = TextModel.Computed('Time', '时间')
    static readonly Type = TextModel.Computed('Type', '类型')
    static readonly Title = TextModel.Computed('Title', '标题')
    static readonly Theme = TextModel.Computed('Theme', '主题')
    static readonly Table = TextModel.Computed('Table', '表格')
    static readonly TagId = TextModel.Computed('TagId', '标签ID')
    static readonly Target = TextModel.Computed('Target', '终点')
    static readonly Timeout = TextModel.Computed('Timeout', '超时')
    static readonly Transfer = TextModel.Computed('Transfer', '调拨')
    static readonly TagType = TextModel.Computed('TagType', '标签类型')
    static readonly TotalMove = TextModel.Computed('TotalMove', '总周转')
    static readonly TagDetail = TextModel.Computed('TagDetail', '标签详情')
    static readonly Temperature = TextModel.Computed('Temperature', '温度')
    static readonly TransferDetail = TextModel.Computed('TransferDetail', '调拨详情')
    // U:
    static readonly Upload = TextModel.Computed('Upload', '上传')
    static readonly Unbind = TextModel.Computed('Unbind', '解绑')
    static readonly Undone = TextModel.Computed('Undone', '未完成')
    static readonly Unknown = TextModel.Computed('Unknown', '未知')
    static readonly Unbound = TextModel.Computed('Unbound', '未绑定')
    static readonly Username = TextModel.Computed('Username', '用户名')
    static readonly UploadedSuccessfully = TextModel.Computed('Uploaded successfully', '上传成功')
    // V:
    static readonly Vehicle = TextModel.Computed('Vehicle', '车辆')
    static readonly Version = TextModel.Computed('Version: V', '版本：V')
    static readonly VerificationCodeLogin = TextModel.Computed('Verification code login', '验证码登录')
    // W:
    static readonly Warning = TextModel.Computed('Warning', '警告')
    // Y:
    static readonly Yes = TextModel.Computed('Yes', '是')
}