export enum MapPlugins {
    /** 灵活点标记 */
    ElasticMarker = 'AMap.ElasticMarker',
    /** 工具条 */
    ToolBar = 'AMap.ToolBar',
    /** 比例尺 */
    Scale = 'AMap.Scale',
    /** 鹰眼 */
    HawkEye = 'AMap.HawkEye',
    /** 组合了旋转、倾斜、复位在内的地图控件 */
    ControlBar = 'AMap.ControlBar',
    /** 图层切换 */
    MapType = 'AMap.MapType',
    /** 浏览器定位 */
    Geolocation = 'AMap.Geolocation',
    /** 输入提示 */
    AutoComplete = 'AMap.AutoComplete',
    /** 地点搜索 */
    PlaceSearch = 'AMap.PlaceSearch',
    /** 行政区查询 */
    DistrictSearch = 'AMap.DistrictSearch',
    /** 公交路线 */
    LineSearch = 'AMap.LineSearch',
    /** 公交站点查询 */
    StationSearch = 'AMap.StationSearch',
    /** 驾车路线规划 */
    Driving = 'AMap.Driving',
    /** 货车路线规划 */
    TruckDriving = 'AMap.TruckDriving',
    /** 公交路线规划 */
    Transfer = 'AMap.Transfer',
    /** 步行路线规划 */
    Walking = 'AMap.Walking',
    /** 骑行路线规划 */
    Riding = 'AMap.Riding',
    /** 拖拽导航 */
    DragRoute = 'AMap.DragRoute',
    /** 地理编码与逆地理编码 */
    Geocoder = 'AMap.Geocoder',
    /** 城市获取 */
    CitySearch = 'AMap.CitySearch',
    /** 室内地图 */
    IndoorMap = 'AMap.IndoorMap',
    /** 鼠标工具 */
    MouseTool = 'AMap.MouseTool',
    /** 圆编辑器 */
    CircleEditor = 'AMap.CircleEditor',
    /** 多边形编辑器 */
    PolygonEditor = 'AMap.PolygonEditor',
    /** 折线编辑器 */
    PolylineEditor = 'AMap.PolylineEditor',
    /** 矩形编辑器 */
    RectangleEditor = 'AMap.RectangleEditor',
    /** 椭圆编辑器 */
    EllipseEditor = 'AMap.EllipseEditor',
    /** 贝塞尔曲线编辑器 */
    BezierCurveEditor = 'AMap.BezierCurveEditor',
    /** 点聚合 */
    MarkerCluster = 'AMap.MarkerCluster',
    /** 测距 */
    RangingTool = 'AMap.RangingTool',
    /** 云图搜索 */
    CloudDataSearch = 'AMap.CloudDataSearch',
    /** 天气预报 */
    Weather = 'AMap.Weather',
    /** 热力图 */
    HeatMap = 'AMap.HeatMap',
    /** 移动动画 */
    MoveAnimation = 'AMap.MoveAnimation',
}
